import { makeStyles } from "@material-ui/core";

const styles = makeStyles({
  frag: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "100vh",
    position: "relative",
    backgroundColor: "#f9f9f9",
  },

  dataHolder: {
    display: "flex",
    width: "90%",
    flexDirection: "column",
    justifyContent: "center",
    marginBottom: "auto",
  },
  item: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-start",
    height: "1.5rem",
    backgroundColor: " #3A3B3C ",
    marginBottom: ".5rem",
    padding: ".3rem",
    borderRadius: "6px",
    "&:hover": {
      backgroundColor: "rgba(0, 0, 0, .20)",
    },
  },
  deleteBtn: {
    marginLeft: "auto",
    backgroundColor: " #d9534f ",
    color: " rgba(9, 30, 66) ",
  },
  itemName: {
    marginRight: "auto",
    color: "#E4E6EB",
    flexGrow: "1",
    cursor: "pointer",
  },

  addButton: {
    backgroundColor: "#242526",
    color: "#E4E6EB",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    margin: "1rem",

    borderColor: "#E4E6EB",
    cursor: "pointer",
    "&:hover": {
      color: "#3A3B3C",
    },
  },
  backButton: {
    backgroundColor: "#242526",
    color: "#E4E6EB",
    display: "flex",
    cursor: "pointer",
    "&:hover": {
      color: "#3A3B3C",
    },
  },
  mainBtns: {
    display: "flex",
    justifyContent: "space-around",
    width: "80%",
  },
  mainBtnsform: {
    display: "flex",
    justifyContent: "space-around",
    alignItems: "center",
    width: "100%",
    marginTop: "3rem",
  },
  formContainer: {
    backgroundColor: "blue",
    zIndex: "1",
    position: "relative",
    display: "flex",
    alignItems: "center",
    background: "#242526",
    borderRadius: "2rem",
    height: "40rem",
    width: "40rem",
    margin: "auto",
    marginBottom: "7rem",
    flexDirection: "column",
    top: "-85vh",
  },
  formDiv: {
    display: "flex",
    justifyContent: "flex-start",
    alignItems: "center",
  },

  selectContainer: {
    display: "flex",
    justifyContent: "flex-start",
    alignItems: "center",
    paddingBottom: "5rem",
  },
  selectDiv: {
    width: "12rem",
    "& div": {
      backgroundColor: "#3A3B3C",
      color: "#E4E6EB",
    },
  },
  typoText: {
    color: "#E4E6EB",
    paddingRight: "1rem",
  },
  dataHolder: {
    display: "flex",
    width: "90%",
    flexDirection: "column",
    justifyContent: "center",
    marginBottom: "auto",
  },
  formfields: {
    display: "flex",
    justifyContent: "space-around",
    flexDirection: "column",
    height: "100%",
    width: "90%",
  },
  navigationBtns: {
    display: "flex",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    flexDirection: "column",
  },
  navigationBtn: {
    color: "#E4E6EB",
    borderColor: "#E4E6EB",
    margin: "1rem",
  },
  // Shorter MakeShorter
  containerMulti: {
    display: "flex",
    position: "absolute",
    justifyContent: "center",
    alignItems: "center",
    background: "#fff",
    boxShadow: "0 1px 4px #ccc",
    // background:
    // "linear-gradient(45deg, rgba(63,81,181,1) 33%, rgba(7,132,201,1) 100%)",
    borderRadius: "2rem",
    height: "50rem",
    width: "50rem",
    margin: "auto",
    marginBottom: "7rem",
    flexDirection: "column",
  },
  containerSingle: {
    display: "flex",
    position: "absolute",
    justifyContent: "center",
    alignItems: "center",
    background: "#fff",
    boxShadow: "0 1px 4px #ccc",
    // background:
    // "linear-gradient(45deg, rgba(63,81,181,1) 33%, rgba(7,132,201,1) 100%)",
    borderRadius: "2rem",
    height: "30rem",
    width: "40rem",
    marginBottom: "7rem",
    flexDirection: "column",
  },

  singleOrMulti: {
    textAlign: "center",
    fontWeight: "bold",
    color: "#fff",
    fontSize: "1.5rem",
    borderStyle: "solid",
    borderRadius: "5px",
    padding: ".5rem",
    borderColor: "#2c87c5",
    marginTop: ".5rem",
    marginBottom: ".5rem",
    marginRight: ".5rem",
    backgroundColor: "#2c87c5",
    cursor: "pointer",
    "&:hover": {
      backgroundColor: "rgba(30, 93,132, .90)",
      borderColor: "rgba(30, 93,132, .90)",
    },
  },
  title: {
    textAlign: "center",
    fontFamily: "Roboto Mono",
    color: "#505050",
    fontSize: "2rem",
    fontWeight: "bold",
    marginRight: ".5rem",
    marginBottom: "3rem",
  },
  titleLinks: {
    textAlign: "center",
    fontFamily: "Roboto Mono",
    color: "#505050",
    fontSize: "1rem",
    fontWeight: "bold",
  },
  titleMulti: {
    textAlign: "center",
    width: "20%",
    fontFamily: "Roboto Mono",
    color: "#505050",
    fontSize: "1.2rem",
    fontWeight: "bold",
    marginRight: ".5rem",
    marginBottom: "3rem",
  },
  shorterBtn: {
    width: "85%",
    backgroundColor: "#2c87c5",
    "&:hover": {
      backgroundColor: "rgba(30, 93,132, .90)",
      borderColor: "rgba(30, 93,132, .90)",
    },
    margin: "auto",
  },
  multiOrSingleContainer: {
    display: "felx",
    justifyContent: "flex-start",
    alignItems: "center",
    margin: "1rem",
  },
  formShorter: {
    display: "flex",
    height: "65%",
    width: "100%",
  },
  formShorterlinks: {
    display: "flex",
    height: "65%",
    width: "100%",
    border: "1px",
    borderColor: "grey",
    borderStyle: "solid",
    alignItems: "center",
    marginBottom: ".2rem",
    flexDirection: "column",
  },
  shorterForm: {
    display: "flex",
    height: "65%",
    width: "100%",
    flexDirection: "column",
  },
  multiContainers: {
    display: "flex",
    justifyContent: "flex-start",
    flexDirection: "row",
    alignItems: "center",
  },
  textAddField: {
    backgroundColor: "#fff",
    width: "85%",
    color: "#505050",
    "& label": {
      color: "#505050",
      zIndex: "0",
    },
  },
  textAddFieldMulti: {
    backgroundColor: "#fff",
    width: "75%",
    color: "#505050",
    "& label": {
      color: "#505050",
      zIndex: "0",
    },
    marginBottom: "3rem",
  },
});
export default styles;
