import { makeStyles } from "@material-ui/core";

const styles = makeStyles({
  frag: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "100vh",
    position: "relative",
    backgroundColor: "#18191A",
  },
  container: {
    display: "flex",
    position: "absolute",
    justifyContent: "center",
    alignItems: "center",
    background: "#242526",
    // background:
    // "linear-gradient(45deg, rgba(63,81,181,1) 33%, rgba(7,132,201,1) 100%)",
    borderRadius: "2rem",
    height: "40rem",
    width: "40rem",
    margin: "auto",
    marginBottom: "7rem",
    flexDirection: "column",
  },
  dataHolder: {
    display: "flex",
    width: "90%",
    flexDirection: "column",
    justifyContent: "center",
    marginBottom: "auto",
  },
  item: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-start",
    height: "1.5rem",
    backgroundColor: " #3A3B3C ",
    marginBottom: ".5rem",
    padding: ".3rem",
    borderRadius: "6px",
    "&:hover": {
      backgroundColor: "rgba(0, 0, 0, .20)",
    },
  },
  deleteBtn: {
    marginLeft: "auto",
    backgroundColor: " #d9534f ",
    color: " rgba(9, 30, 66) ",
  },
  itemName: {
    marginRight: "auto",
    color: "#E4E6EB",
    flexGrow: "1",
    cursor: "pointer",
  },
  title: {
    textAlign: "center",
    color: "#B0B3B8",
    fontSize: "1.5rem",
    borderStyle: "solid",
    borderRadius: "5px",
    borderColor: "#B0B3B8",
    padding: ".5rem",
    marginTop: ".5rem",
    marginBottom: ".5rem",
  },
  addButton: {
    backgroundColor: "#242526",
    color: "#E4E6EB",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    margin: "1rem",

    borderColor: "#E4E6EB",
    cursor: "pointer",
    "&:hover": {
      color: "#3A3B3C",
    },
  },
  backButton: {
    backgroundColor: "#242526",
    color: "#E4E6EB",
    display: "flex",
    cursor: "pointer",
    "&:hover": {
      color: "#3A3B3C",
    },
  },
  mainBtns: {
    display: "flex",
    justifyContent: "space-around",
    width: "80%",
  },
  mainBtnsform: {
    display: "flex",
    justifyContent: "space-around",
    alignItems: "center",
    width: "100%",
    marginTop: "3rem",
  },
  formContainer: {
    backgroundColor: "blue",
    zIndex: "1",
    position: "relative",
    display: "flex",
    alignItems: "center",
    background: "#242526",
    borderRadius: "2rem",
    height: "40rem",
    width: "40rem",
    margin: "auto",
    marginBottom: "7rem",
    flexDirection: "column",
    top: "-85vh",
  },
  formDiv: {
    display: "flex",
    justifyContent: "flex-start",
    alignItems: "center",
  },
  textAddField: {
    backgroundColor: "#3A3B3C",
    color: "#E4E6EB",
    "& label": {
      color: "#E4E6EB",
      zIndex: "0",
    },
  },
  selectContainer: {
    display: "flex",
    justifyContent: "flex-start",
    alignItems: "center",
    paddingBottom: "5rem",
  },
  selectDiv: {
    width: "12rem",
    "& div": {
      backgroundColor: "#3A3B3C",
      color: "#E4E6EB",
    },
  },
  typoText: {
    color: "#E4E6EB",
    paddingRight: "1rem",
  },
  dataHolder: {
    display: "flex",
    width: "90%",
    flexDirection: "column",
    justifyContent: "center",
    marginBottom: "auto",
  },
  formfields: {
    display: "flex",
    justifyContent: "space-around",
    flexDirection: "column",
    height: "100%",
    width: "90%",
  },
  navigationBtns: {
    display: "flex",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    flexDirection: "column",
  },
  navigationBtn: {
    color: "#E4E6EB",
    borderColor: "#E4E6EB",
    margin: "1rem",
  },
});
export default styles;
